
services:
  node-app:
    container_name: node-app-container
    build: .
    volumes: 
      - ./src:/app/src:ro
    ports:
      - "4000:4000"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1598753
      MYSQL_USER: ismailsamy
      MYSQL_PASSWORD: 1598753
      MYSQL_DATABASE: databasenginx
 
    volumes:
    - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
    
    expose:
      - "80"
    networks:
      - app-network
    depends_on:
      - mysql
 
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network
    depends_on:
      - mysql
      - phpmyadmin

networks:
  app-network:
    driver: bridge 