    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (Jenkins dependency)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Install OpenSSH Server
      apt:
        name: openssh-server
        state: present

    - name: Install Node.js (for JavaScript dependencies)
      apt:
        name: nodejs
        state: present

    - name: Install npm (Node.js package manager)
      apt:
        name: npm
        state: present

    - name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        state: started
        enabled: yes
